chore: introduce `(Lwt)Label` type (reduce stringly typing) (#228)
* chore: introduce `Label` type (reduce stringly typing)

* fix py39 error

ImportError: cannot import name 'TypeAlias' from 'typing' (/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/typing.py)

* pylint

* black

---------

Co-authored-by: Konstantin <konstantin.klein+github@hochfrequenz.de>